server:
  port: 9092
  
spring:
  data:
    mongodb:
      uri: mongodb+srv://root:WBJsDZphl9loQGt4@mongodb.lqmn4.mongodb.net/onboarding-prudential?retryWrites=true&w=majority
  application:
    name: ASSOCIATE-SERVICE
  config:
        activate:
            on-profile: dev
#  zipkin:
#    base-url: http://127.0.0.1:9411/
    
logging:
  file.name: C:/Users/003EMS744/DriveSetup/logs/associate-service.log

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url: 
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
   
  